"use client";

import Image from "next/image";
import { useState } from "react";
import { ArrowUpRight, Check, Download, LockKeyhole, Video, Wallet, Upload, X, CalendarDays, Sparkles } from "lucide-react";
import { Sidebar } from "@/components/Sidebar";
import styles from "./studio.module.css";
import { StudioMemberships, StudioTickets } from "@/components/StudioMemberships";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";

const sections = ["Creator card", "Productos", "Reservas", "Tickets NFT", "Pagos USDC", "Suscripciones", "Mainnet"];
const products = [{name:"Creator toolkit",type:"Guía PDF + recursos",price:19,image:"/asset-artbymaria.png"},{name:"Sesión creativa",type:"Videollamada de 30 minutos",price:35,image:"/asset-cryptocoach.png"},{name:"Studio club",type:"Contenido para miembros",price:12,image:"/asset-lunasol.png"}];

export default function StudioPage() {
  const [section,setSection]=useState(0);
  const [dialog,setDialog]=useState<number|null>(null);
  const [notice,setNotice]=useState("");
  const [day,setDay]=useState("12 oct");
  const [time,setTime]=useState("15:00");
  const [paid,setPaid]=useState(false);
  const [file,setFile]=useState("");
  const [delivery,setDelivery]=useState(false);
  const [checks,setChecks]=useState<boolean[]>([false,false,false,false]);
  function change(index:number){setSection(index);setNotice("");}
  function simulate(message:string){setNotice(message);}
  return <div className={styles.shell}><Sidebar/><main className={styles.main}>
    <header className={styles.top}><a href="#studio-content" className={styles.skip}>Saltar al contenido</a><span>VYNX / CREATOR STUDIO</span><span className={styles.demo}>Prototipo interactivo · datos de ejemplo</span></header>
    <div className={styles.heading}><div><p className={styles.eyebrow}>TU ESPACIO. TUS REGLAS.</p><h1>Una card.<br/><em>Todo tu universo.</em></h1><p>Explora la experiencia del próximo MVP, desde tu oferta hasta la entrega.</p></div><div className={styles.stamp}><Sparkles/><strong>Diseñado para crear</strong><span>Identidad propia, comunidad conectada.</span></div></div>
    <nav className={styles.tabs} aria-label="Pantallas del prototipo">{sections.map((label,index)=>({label,index})).filter(({index})=>index!==4&&index!==6).map(({label,index},position)=><button key={label} aria-pressed={section===index} onClick={()=>change(index)}>{String(position+1).padStart(2,"0")} <span>{label}</span></button>)}</nav>
    <div id="studio-content" className={styles.content}>
    {section===0?<div className={styles.showcase}><article className={styles.creator}><div className={styles.portrait}><Image src="/asset-lunasol.png" alt="Retrato ilustrativo de Luna, creadora de ejemplo" fill sizes="(max-width: 800px) 100vw, 420px" priority/><span className={styles.live}>Creator preview</span></div><div className={styles.identity}><p className={styles.eyebrow}>@LUNASTUDIO</p><h2>Luna Studio <span>✦</span></h2><p>Diseño, ideas y conversaciones.<br/>Un espacio para quienes crean conmigo.</p><div className={styles.offerList}>{products.map((p,i)=><button key={p.name} onClick={()=>{setDialog(i);setPaid(false);}}><span>{i===0?<Download/>:i===1?<Video/>:<LockKeyhole/>}{p.name}</span><span>{p.price} USDC <ArrowUpRight size={15}/></span></button>)}</div><div className={styles.social}><a href="https://instagram.com" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://youtube.com" target="_blank" rel="noopener noreferrer">YouTube ↗</a></div></div></article><section className={styles.editorial}><p className={styles.eyebrow}>CREATOR CARD / NUEVA DIRECCIÓN</p><h2>Tu marca al frente.<br/><em>Tu oferta, a un clic.</em></h2><p>Una imagen protagonista, ofertas claras y una experiencia consistente en móvil y escritorio.</p><div className={styles.smallCards}>{products.map((p,i)=><button key={p.name} onClick={()=>change(i===0?1:i===1?2:5)}><Image src={p.image} alt="" width={180} height={180}/><span>{p.type}</span><strong>{p.name}</strong><span className={styles.price}>{p.price} USDC <ArrowUpRight size={16}/></span></button>)}</div><p className={styles.caption}>Perfil ficticio. Precios ilustrativos. Explora las ofertas para ver sus pantallas.</p></section></div>:<>
      <div className={styles.sectionTitle}><div><p className={styles.eyebrow}>PANTALLA {String(section+1).padStart(2,"0")}</p><h2>{sections[section]}</h2></div><span className={styles.demo}>Vista de demostración</span></div>
      {section===1&&<div className={styles.twoCol}><form className={styles.panel} onSubmit={e=>{e.preventDefault();simulate("Producto guardado en esta demostración. La subida y entrega reales todavía no están conectadas.");}}><Upload className={styles.icon}/><h3>Publicar un producto digital</h3><label>Título<input required placeholder="Creator toolkit" maxLength={80}/></label><label>Descripción<textarea required placeholder="Qué incluye y para quién es" rows={3}/></label><div className={styles.fields}><label>Precio en USDC<input type="number" min="1" step="0.01" defaultValue="19" required/></label><label>Formato<select><option>PDF</option><option>ZIP</option><option>Video</option></select></label></div><label className={styles.upload}>Seleccionar archivo<input type="file" accept=".pdf,.zip,.mp4" onChange={e=>setFile(e.target.files?.[0]?.name??"")}/><span>{file||"PDF, ZIP o MP4 · selección local, sin subida"}</span></label><button className={styles.primary}>Guardar producto de ejemplo</button></form><div className={styles.panel}><Image className={styles.productImage} src="/asset-artbymaria.png" alt="Portada ilustrativa del toolkit" width={600} height={300}/><p className={styles.eyebrow}>EXPERIENCIA DEL COMPRADOR</p><h3>Creator toolkit</h3><p>Guía PDF y recursos para preparar tu próxima colaboración.</p><strong className={styles.bigPrice}>19 USDC</strong><button className={styles.primary} onClick={()=>{setDialog(0);setPaid(false);}}>Ver checkout <ArrowUpRight size={16}/></button><p className={styles.caption}>La entrega se habilitaría después de verificar el pago.</p></div></div>}
      {section===2&&<div className={styles.twoCol}><section className={styles.panel}><CalendarDays className={styles.icon}/><h3>Reserva tu sesión creativa</h3><p>30 minutos con Luna Studio · 35 USDC</p><h4>Elegí un día</h4><div className={styles.choices}>{["12 oct","13 oct","14 oct"].map(d=><button key={d} aria-pressed={day===d} onClick={()=>setDay(d)}>{d}</button>)}</div><h4>Horario · Buenos Aires (UTC−3)</h4><div className={styles.choices}>{["15:00","16:00","17:30"].map(t=><button key={t} aria-pressed={time===t} onClick={()=>setTime(t)}>{t}</button>)}</div><button className={styles.primary} onClick={()=>{setDialog(1);setPaid(false);}}>Continuar con {day}, {time}</button><p className={styles.caption}>Horarios de ejemplo. No se crean reservas reales.</p></section><section className={styles.call}><Image src="/asset-cryptocoach.png" alt="Participante ilustrativo" fill sizes="(max-width: 800px) 100vw, 600px"/><div><span>PREVIEW / SALA DE VIDEOLLAMADA</span><h3>Nos vemos en tu próxima idea.</h3><button onClick={()=>simulate("Vista de sala preparada. La videollamada real requiere integrar un proveedor.")}><Video/>Explorar sala de ejemplo</button></div></section></div>}
      {section===3&&<StudioTickets/>}
      {section===4&&<div className={styles.twoCol}><section className={styles.panel}><Wallet className={styles.icon}/><h3>Un checkout con precio claro</h3><div className={styles.receipt}><span>Creator toolkit</span><strong>19 USDC</strong><span>Red de la demostración</span><strong>Solana devnet</strong><span>Comisión de red</span><strong>Se calcula al preparar el pago</strong></div><p>La wallet mostrará el importe y el destinatario antes de que el comprador confirme.</p><button className={styles.primary} onClick={()=>{setDialog(0);setPaid(false);}}>Explorar estados del pago</button></section><section className={styles.panel}><p className={styles.eyebrow}>PAGO Y ENTREGA</p><h3>Cada paso tiene un estado</h3>{["Preparar transacción","Firma del comprador","Confirmación en Solana","Habilitar entrega"].map((t,i)=><div className={styles.step} key={t}><span>{i+1}</span><strong>{t}</strong></div>)}<p className={styles.caption}>El flujo de patrocinios actual usa devnet. Este checkout de productos es un mockup.</p></section></div>}
      {section===5&&<StudioMemberships/>}
      {section===6&&<div className={styles.twoCol}><section className={styles.panel}><p className={styles.eyebrow}>PREPARACIÓN PARA MAINNET</p><h3>Un lanzamiento que podamos verificar.</h3><p>Checklist de planificación. No cambia la red del producto.</p>{["Probar pagos y entregas de extremo a extremo","Revisar permisos, protección de archivos y acceso","Definir cancelaciones y reembolsos","Configurar mainnet y realizar una prueba controlada"].map((c,i)=><label className={styles.check} key={c}><input type="checkbox" checked={checks[i]} onChange={()=>setChecks(checks.map((v,j)=>j===i?!v:v))}/>{c}</label>)}</section><section className={styles.panel}><p className={styles.eyebrow}>ESTADO DEL LANZAMIENTO</p><h3>{checks.filter(Boolean).length} / 4 pasos revisados</h3><progress max={4} value={checks.filter(Boolean).length}/><p>Red actual: <strong>Solana devnet</strong></p><p>El checklist es local a esta sesión y no constituye una aprobación de lanzamiento.</p><a className={styles.primary} href="/dashboard/sponsorships">Ir al MVP actual <ArrowUpRight size={16}/></a></section></div>}
    </>}
    {notice&&<p className={styles.notice} role="status">{notice}</p>}
    {section===1&&<section className={styles.panel} style={{marginTop:24}}><p className={styles.eyebrow}>BIBLIOTECA DEL COMPRADOR</p><h3>{delivery?"Tu recurso está listo":"Entrega después del pago"}</h3><p>{delivery?"Creator toolkit · PDF y recursos · pedido de ejemplo confirmado.":"Los archivos permanecen protegidos hasta que el servidor verifica el pago."}</p><button className={styles.secondary} onClick={()=>{setDelivery(!delivery);simulate(delivery?"Ejemplo de entrega bloqueada.":"Entrega simulada habilitada. No hay un archivo comprado ni un pago real.");}}>{delivery?"Ver estado bloqueado":"Simular entrega habilitada"}</button>{delivery&&<button className={styles.primary} onClick={()=>simulate("Ejemplo: aquí se generaría un enlace de descarga temporal para el comprador autorizado.")}>Ver descarga protegida <Download size={16}/></button>}</section>}
    </div><footer className={styles.footer}>VYNX STUDIO <span>Mockups del roadmap · sin transacciones ni subida de archivos</span></footer>
    <Dialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null);}}>{dialog!==null&&<DialogContent className={styles.modal}><button autoFocus className={styles.close} aria-label="Cerrar checkout" onClick={()=>setDialog(null)}><X/></button><p className={styles.eyebrow}>CHECKOUT DE EJEMPLO</p><DialogTitle>{paid?"Todo listo en esta demo":products[dialog].name}</DialogTitle><p>{products[dialog].type}</p><div className={styles.receipt}><span>Total ilustrativo</span><strong>{products[dialog].price} USDC</strong><span>Red</span><strong>Devnet / simulación</strong></div>{paid?<><Check className={styles.icon}/><p>Pago simulado. No se firmó ni envió una transacción.</p><button className={styles.primary} onClick={()=>{setDialog(null);change(dialog===0?1:dialog===1?2:5);simulate(dialog===0?"Entrega de ejemplo preparada. No existe un archivo de compra real.":dialog===1?`Reserva simulada: ${day} a las ${time}.`:"Membresía de ejemplo lista para explorar.");}}>Ver {dialog===0?"entrega":dialog===1?"reserva":"membresía"}</button></>:<button className={styles.primary} onClick={()=>setPaid(true)}>Simular pago confirmado</button>}<p className={styles.caption}>Vista de diseño. No conectamos tu wallet ni movemos fondos.</p></DialogContent>}</Dialog>
  </main></div>;
}


