'use client';

import Image from 'next/image';
import Link from 'next/link';
import { BrandLogo } from '@/components/BrandLogo';
import { ArrowLeft, ArrowUpRight, Check, Clock3, Globe, Link2, Pause, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import SponsorshipWalletControl from '@/components/SponsorshipWalletControl';
import { useSponsorshipWallet } from '@/lib/use-sponsorship-wallet';
import { safeLink, type CreatorDraft } from '@/lib/creator-draft';
import { money, type SponsorProfile } from '@/lib/sponsorship-domain';

export type PublicAd = { id: string; brand_name: string; headline: string; description: string; destination_url: string; ends_at: string };
const input = 'mt-2 w-full rounded-xl border border-current/15 bg-current/5 px-4 py-3 text-sm outline-none placeholder:opacity-40 focus:ring-2 focus:ring-violet-400';

export function CreatorPublicView({ profile, ad, design, preview = false, onRequest, busy = false, notice = '', failed = false }: {
  profile: SponsorProfile; ad: PublicAd | null; design?: CreatorDraft; preview?: boolean;
  onRequest?: (event: FormEvent<HTMLFormElement>) => void; busy?: boolean; notice?: string; failed?: boolean;
}) {
  const { wallet, open } = useSponsorshipWallet();
  const [description, setDescription] = useState('');
  const accent = design ? {mint:'#00F5A0',violet:'#b69aff',rose:'#ff94b9'}[design.accent] : '#00F5A0';
  const light = design?.theme === 'light';
  const card = `rounded-3xl border border-current/10 ${light ? 'bg-white' : 'bg-[#101015]'}`;
  const button = `inline-flex items-center justify-center gap-2 px-5 py-3 text-sm font-semibold transition hover:brightness-110 disabled:opacity-40 ${design?.rounded === false ? 'rounded-md' : 'rounded-xl'}`;
  const links = design?.links ?? (profile.website ? [{id:'website',title:'Mi sitio y mis proyectos',url:profile.website}] : []);
  const socials = design ? Object.entries(design.socials).filter(([,url]) => safeLink(url)) : [];
  const ownPage = wallet === profile.wallet;

  return <main className={`min-h-screen px-5 py-6 sm:px-8 ${light ? 'bg-[#f5f5f7] text-zinc-900' : 'bg-[#07070a] text-white'}`}>
    <div className="mx-auto max-w-6xl">
      <nav aria-label="Navegación de la página pública" className="mb-8 flex flex-wrap items-center justify-between gap-4"><BrandLogo light={light} /><div className="flex flex-wrap items-center gap-4">{preview ? <Link href="/dashboard/mypage" className="inline-flex items-center gap-2 text-sm opacity-60"><ArrowLeft size={15} />Volver al editor</Link> : <><Link href="/dashboard/sponsorships" className="text-xs opacity-60">Mis patrocinios ↗</Link><SponsorshipWalletControl /></>}</div></nav>
      {preview && <p role="status" className="mb-6 rounded-xl border border-violet-400/30 bg-violet-400/10 p-4 text-sm leading-6">Vista previa local · solo tú ves este borrador en este navegador. No está publicado y no permite enviar propuestas. El precio se configura en Patrocinios.</p>}
      <div className="grid gap-7 lg:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
        <div className="min-w-0 space-y-6">
          <section className={`${card} overflow-hidden`}>
            <div className="relative h-40 overflow-hidden sm:h-52" style={{background:`linear-gradient(120deg, ${accent}55, #362056 60%, #17151e)`}}>{design?.cover ? <Image src={design.cover} alt="Portada del creador" fill unoptimized sizes="(max-width:1024px) 100vw, 650px" className="object-cover" /> : <div aria-hidden="true" className="absolute -right-12 -top-20 size-80 rounded-full border-[45px] border-white/5" />}</div>
            <div className="relative -mt-12 px-6 pb-7 sm:px-8 sm:pb-8"><div className={`relative flex size-24 items-center justify-center overflow-hidden rounded-3xl border-4 ${light ? 'border-white bg-zinc-100' : 'border-[#101015] bg-[#202027]'}`}>{design?.avatar ? <Image src={design.avatar} alt={`Foto de ${profile.display_name}`} fill sizes="96px" unoptimized className="object-cover" /> : <span className="text-3xl font-semibold" style={{color:accent}}>{profile.display_name.slice(0,1).toUpperCase() || <UserRound size={32} />}</span>}</div>
              <p className="mt-5 break-all text-xs font-medium" style={{color:light ? '#6240a6' : accent}}>@{profile.alias}</p><h1 className="mt-2 break-words text-3xl font-semibold tracking-tight sm:text-4xl">{profile.display_name}</h1><p className="mt-4 whitespace-pre-line break-words text-sm leading-7 opacity-65">{profile.bio || 'Un espacio para compartir lo que creo y conectar con mi comunidad.'}</p>
              {socials.length > 0 && <nav aria-label="Redes del creador" className="mt-5 flex flex-wrap gap-2">{socials.map(([network,url]) => <a key={network} href={safeLink(url)!} target="_blank" rel="noopener noreferrer" className="rounded-full border border-current/15 px-3 py-2 text-xs opacity-65 hover:opacity-100">{network === 'x' ? 'X' : network === 'youtube' ? 'YouTube' : 'Instagram'}<span className="sr-only">, abre en otra pestaña</span></a>)}</nav>}
              {links.length > 0 && <div className="mt-6 space-y-3">{links.filter(link => safeLink(link.url)).map(link => <a key={link.id} href={safeLink(link.url)!} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl border border-current/10 px-4 py-4 text-sm transition hover:bg-current/5"><Globe size={18} className="shrink-0 opacity-50" aria-hidden="true" /><span className="min-w-0 flex-1 break-words">{link.title}</span><ArrowUpRight size={17} aria-hidden="true" className="shrink-0 opacity-50" /></a>)}</div>}
            </div>
          </section>
          <section className={`${card} p-6 sm:p-8`}>
            {ad ? <><div className="flex flex-wrap items-center justify-between gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-violet-400/10 px-3 py-1.5 text-[10px] font-medium uppercase tracking-widest"><Sparkles size={12} />Patrocinado</span><span className="text-xs opacity-50">Elegido por el creador</span></div><p className="mt-6 break-words text-xs font-medium opacity-50">{ad.brand_name}</p><h2 className="mt-2 break-words text-2xl font-semibold">{ad.headline}</h2><p className="mt-3 break-words text-sm leading-7 opacity-65">{ad.description}</p><a href={ad.destination_url} target="_blank" rel="noopener noreferrer sponsored" className={`${button} mt-6 text-black`} style={{background:accent}}>Conocer la marca<ArrowUpRight size={16} /></a></> : <><span className="inline-flex items-center gap-2 text-xs opacity-50"><Sparkles size={16} aria-hidden="true" />Colaboraciones con propósito</span><h2 className="mt-4 text-2xl font-semibold">{profile.accepting ? 'Tu marca, parte de este espacio.' : 'Cada colaboración, a su tiempo.'}</h2><p className="mt-3 text-sm leading-7 opacity-65">{profile.accepting ? 'Una propuesta que conecte con esta comunidad. Un anuncio elegido por el creador, publicado aquí durante el período acordado.' : 'Este creador pausó las propuestas. Puedes explorar sus enlaces y volver más adelante.'}</p>{profile.accepting && <a href="#propuesta" className="mt-5 inline-flex items-center gap-2 text-sm font-medium">Conocer la oferta<ArrowUpRight size={16} /></a>}</>}
          </section><p className="px-2 text-xs leading-6 opacity-40">Los patrocinios se muestran en esta página de Vynx. No se publican automáticamente en las redes del creador.</p>
        </div>
        <section id="propuesta" className={`${card} min-w-0 self-start scroll-mt-6 p-6 sm:p-8 lg:sticky lg:top-6`}>
          <span className="inline-flex items-center gap-2 rounded-full border border-current/10 px-3 py-1.5 text-[10px] font-medium uppercase tracking-widest"><span className={`size-1.5 rounded-full ${profile.accepting ? 'bg-emerald-400' : 'bg-amber-400'}`} />{preview ? 'Oferta por configurar' : profile.accepting ? 'Recibe propuestas' : 'Propuestas pausadas'}</span><h2 className="mt-5 text-2xl font-semibold">Colabora con este creador</h2><p className="mt-2 text-sm leading-6 opacity-50">Un espacio exclusivo. Una marca a la vez.</p>
          <div className="my-6 border-y border-current/10 py-5"><p className="text-3xl font-semibold tracking-tight">{preview ? 'Precio por definir' : money(profile.price_cents)}{!preview && <span className="ml-2 text-sm font-normal opacity-50">USDC de prueba</span>}</p><p className="mt-3 inline-flex items-center gap-2 text-xs opacity-50"><Clock3 size={14} aria-hidden="true" />{preview ? 'Duración por definir' : `${profile.duration_days} días de publicación desde el pago verificado`}</p></div>
          <ol className="mb-6 grid grid-cols-3 gap-2 text-[10px] opacity-60">{['Envía tu propuesta','El creador aprueba','Pagas y se publica'].map((label,index) => <li key={label}><span className="mb-2 flex size-6 items-center justify-center rounded-full border border-current/15">{index + 1}</span>{label}</li>)}</ol>
          <p className="rounded-xl bg-violet-400/10 p-3 text-xs leading-5 opacity-70">Solana devnet · tokens sin valor monetario. El precio corresponde al período de publicación; no garantiza visitas ni ventas.</p>
          {preview ? <div className="mt-6 rounded-xl border border-dashed border-current/15 p-5 text-sm leading-6 opacity-60">Aquí las marcas podrán enviarte una propuesta cuando publiques tu oferta.<Link href="/dashboard/sponsorships" className="mt-3 flex items-center gap-2 font-medium">Configurar mi oferta<ArrowUpRight size={15} /></Link></div> : !profile.accepting ? <div className="mt-6 flex gap-3 rounded-xl border border-current/10 p-4"><Pause size={19} className="shrink-0 opacity-50" aria-hidden="true" /><p className="text-sm leading-6 opacity-65">Las propuestas están pausadas. Vuelve más adelante para colaborar.</p></div> : ownPage ? <div className="mt-6 text-sm leading-6 opacity-65">Esta es tu página. Revisa las propuestas y administra tu oferta desde el panel.<Link href="/dashboard/sponsorships" className="mt-4 flex items-center gap-2 font-medium">Gestionar patrocinios<ArrowUpRight size={15} /></Link></div> : notice && !failed ? <div role="status" className="mt-6 rounded-xl border border-emerald-400/30 p-5"><Check size={22} className="mb-3 text-emerald-400" aria-hidden="true" /><p className="text-sm leading-6">{notice}</p><Link href="/dashboard/sponsorships" className="mt-4 inline-flex items-center gap-2 text-sm font-medium">Seguir mi propuesta<ArrowUpRight size={15} /></Link></div> : <form onSubmit={event => { onRequest?.(event); }} className="mt-6 space-y-4">
            <fieldset disabled={busy} className="space-y-4 disabled:opacity-60"><legend className="mb-4 text-sm font-semibold">Tu propuesta</legend><label className="block text-xs opacity-75">Nombre de tu marca<input name="brand_name" required maxLength={60} placeholder="Tu marca" className={input} autoComplete="organization" /></label><label className="block text-xs opacity-75">Título del anuncio<input name="headline" required maxLength={100} placeholder="Una idea que conecte con esta comunidad" className={input} /></label><label className="block text-xs opacity-75">Descripción<textarea name="description" required maxLength={240} rows={3} value={description} onChange={e => setDescription(e.target.value)} placeholder="Cuenta qué ofreces y por qué encaja aquí" className={`${input} resize-y`} /><span className="mt-1 block text-right text-[10px] opacity-50">{description.length} / 240</span></label><label className="block text-xs opacity-75">Enlace de destino<input name="destination_url" required type="url" maxLength={500} pattern="https://.*" placeholder="https://tu-marca.com" className={input} /><span className="mt-2 block text-[10px] opacity-50">El enlace al que llevará tu anuncio. Usa HTTPS.</span></label>
              {wallet ? <button disabled={busy} className={`${button} w-full text-black`} style={{background:accent}}>{busy ? 'Enviando propuesta…' : 'Enviar propuesta · sin pago'}{!busy && <ArrowUpRight size={16} />}</button> : <button type="button" onClick={open} className={`${button} w-full text-black`} style={{background:accent}}>Conectar wallet para proponer<ArrowUpRight size={16} /></button>}
            </fieldset>{notice && <p role={failed ? 'alert' : 'status'} className={`rounded-xl border p-3 text-xs leading-6 ${failed ? 'border-red-400/30 text-red-400' : 'border-emerald-400/30 text-emerald-500'}`}>{!failed && <Check size={15} className="mb-1" />}{notice}</p>}
          </form>}
          <p className="mt-5 flex items-start gap-2 text-[10px] leading-5 opacity-45"><ShieldCheck size={14} className="mt-0.5 shrink-0" />Puedes explorar sin wallet. Conectarla permite firmar tu propuesta; el pago se realiza después de la aprobación.</p>
        </section>
      </div><footer className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-current/10 py-6 text-xs opacity-40"><p>Un espacio propio. Una comunidad conectada.</p><Link href="/dashboard/mypage" className="inline-flex items-center gap-1">Crea tu espacio en Vynx<Link2 size={12} /></Link></footer>
    </div>
  </main>;
}
